/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OregonTrail;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author a-seda
 */
public class ImageLabel extends JLabel {

    private final int NUMBER_OF_LOCATIONS = 19;
    private ImageIcon[] location = new ImageIcon[ NUMBER_OF_LOCATIONS ];
    /**
     * Creates new form ImageLabel
     */
    public ImageLabel() {
        initComponents();
        
        for ( int i = 0; i <=  8; i++ ) {
        String filename = "/images/" + i + ".jpg";
        location[i] = new ImageIcon( this.getClass().getResource(filename));
       
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/0.jpg"))); // NOI18N
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
