/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OregonTrail;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

/**
 *
 * @author Skye
 */
public class OregonTrailJFrame extends javax.swing.JFrame {
    
    private GameMaster master;
    
    private final int NUMBER_OF_LOCATIONS = 8;
    private ImageLabel[] myLOCSet = new ImageLabel[NUMBER_OF_LOCATIONS];
   
    /**
     * Creates new form OregonTrailJFrame
     */
    public OregonTrailJFrame() {
        initComponents();
        master = new GameMaster();
        
        myLOCSet[0] = imageLabel1;
       
        optionsTextArea.setText(master.gameFrameText());
        
        // Temporary just to show where the image should be.
        imagePanel.setBackground(Color.BLUE);
        
        userInputTextField.setText("");
        userInputTextField.requestFocusInWindow();
        
        loadGame();
    }
    
    private void saveGame() {
        
        FileOutputStream fileOut;
        ObjectOutputStream objectOut;
        String name = "oregon.trail";
        
        try { 
            fileOut = new FileOutputStream(name);
            objectOut = new ObjectOutputStream(fileOut);
            objectOut.writeObject(master);
        } 
        catch (FileNotFoundException e) { System.out.println(e); } 
        catch (IOException e) { System.out.println(e); }
        
    }
    
    private void loadGame() {
        
        FileInputStream fileIn;
        ObjectInputStream objectIn;
        String name = "oregon.trail";
        
        try {
            fileIn = new FileInputStream(name);
            objectIn = new ObjectInputStream(fileIn);
            
            this.master = (GameMaster) objectIn.readObject();
        } 
        catch (FileNotFoundException e) { System.out.println(e); }
        catch (IOException e) { System.out.println(e); }
        catch (ClassNotFoundException e) { System.out.println(e); }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel = new javax.swing.JPanel();
        imageLabel1 = new OregonTrail.ImageLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        optionsTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        userOutputTextArea = new javax.swing.JTextArea();
        userInputTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageLabel1.setText("imageLabel1");

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        optionsTextArea.setColumns(20);
        optionsTextArea.setLineWrap(true);
        optionsTextArea.setRows(5);
        jScrollPane1.setViewportView(optionsTextArea);

        userOutputTextArea.setColumns(20);
        userOutputTextArea.setRows(5);
        jScrollPane2.setViewportView(userOutputTextArea);

        userInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userInputTextField)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userInputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputTextFieldActionPerformed
                
        String input = userInputTextField.getText();
        String output = "";
        
        // clean the input so that it is acceptable for use with the software
        //input = cleanString(input);
        
        if(input.isEmpty()) {
            output = "Error: Please give a valid input. \n";
            
            userOutputTextArea.append(output);
        } 
        else if(input.equals("exit") || input.equals("ext")) {
            output = "Player: " + input
                   + "Consol: Thank you for attempting the 'Oregon Trail'.\n"
                   + "        Would you like to save your progress (yes/no)?\n";
        }
        else if(input.equals("save")) {
            saveGame();
        }
        else {
            userOutputTextArea.append(master.runUserInput(input));
            optionsTextArea.setText(master.gameFrameText());
        }
        
        userInputTextField.setText("");
        userInputTextField.requestFocusInWindow();
    }//GEN-LAST:event_userInputTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OregonTrailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OregonTrailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OregonTrailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OregonTrailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OregonTrailJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private OregonTrail.ImageLabel imageLabel1;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea optionsTextArea;
    private javax.swing.JTextField userInputTextField;
    private javax.swing.JTextArea userOutputTextArea;
    // End of variables declaration//GEN-END:variables
}
